# Account data
apiUsername: <username>
apiPasswordHash: <password hash>
apiHost: <emarsys API URL>
apiBase: /v3/
linkDomain: <domain>

# Sender data
senderId: <default>
senderName: <sender name>
senderAddress: <sender e-mail address>

# Path to the recipient file
localRecipientFile:  ./recipients.csv
localRecipientFile2: ./recipients2.csv

fields: [[EMAIL], [RCPT_TYPE_v3, numeric], [LANGUAGE_v3, text]]