# Account data
apiUsername: <username>
apiPasswordHash: <password hash>
apiHost: <emarsys API URL>
apiBase: /v2/
linkDomain: <domain>

# Sender data
senderId: <default>
senderName: <sender name>
senderAddress: <sender e-mail address>

# SFTP data
scpHost: <emarsys SFTP URL>
scpPort: <port>
scpUsername: <SFTP user name>
scpPassword: <SFTP password>
scpDirectory: /home/<SFTP user name>

# Path to the recipient file
localRecipientFile:  ./recipients.csv
localRecipientFile2: ./recipients2.csv

fields: [[EMAIL], [RCPT_TYPE_v2, numeric], [LANGUAGE_v2, text]]
